Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.provider "virtualbox" do |vm|
    vm.gui = false
    vm.memory = 4096
    vm.cpus = 2
  end

  config.vm.define "jrossettS" do |control|
    control.vm.hostname = "jrossettS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vm|
      vm.customize ["modifyvm", :id, "--name", "jrossettS"]
    end
    control.vm.provision "shell", path: "scripts/server.sh"
  end
end
