Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install containerd -y
  SHELL
  config.vm.define "jrossett" do |control|
    control.vm.hostname = "jrossettS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vm|
      vm.customize ["modifyvm", :id, "--name", "jrossett"]
      vm.gui = false
      # vm.memory = "512"
      # vm.cpus = "1"
      vm.memory = "4096"
      vm.cpus = "2"
    end
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      cat /var/lib/rancher/k3s/server/node-token > /vagrant/.env.token
      chown vagrant:vagrant /etc/rancher/k3s/k3s.yaml
      chmod 777 /etc/rancher/k3s/k3s.yaml
    SHELL
  end
  config.vm.define "hubretec" do |control|
    control.vm.hostname = "hubretecSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vm|
      vm.customize ["modifyvm", :id, "--name", "hubretec"]
      vm.gui = false
      # vm.memory = "512"
      # vm.cpus = "1"
      vm.memory = "4096"
      vm.cpus = "2"
    end
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/.env.token) sh -
    SHELL
  end
end
