Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.provider "virtualbox" do |vm|
    vm.gui = false
    vm.memory = 512
    vm.cpus = 1
  end

  config.vm.define "jrossett" do |control|
    control.vm.hostname = "jrossettS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vm|
      vm.customize ["modifyvm", :id, "--name", "jrossett"]
    end
    control.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "hubretec" do |control|
    control.vm.hostname = "hubretecSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vm|
      vm.customize ["modifyvm", :id, "--name", "hubretec"]
    end
    control.vm.provision "shell", path: "scripts/serverWorker.sh"
  end
end
